# Generated by Django 4.2.3 on 2023-07-27 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 27, 21, 8, 1, 531464, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
